spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/blog;DB_CLOSE_ON_EXIT=FALSE
    password: password
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
